# Generated by Django 5.0.1 on 2025-11-09 01:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название проекта')),
                ('slug', models.SlugField(max_length=255, verbose_name='URL-адрес')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('html_content', models.TextField(blank=True, verbose_name='HTML содержимое')),
                ('css_content', models.TextField(blank=True, verbose_name='CSS содержимое')),
                ('json_content', models.JSONField(blank=True, default=dict, verbose_name='JSON данные GrapesJS')),
                ('header_settings', models.JSONField(blank=True, default=dict, verbose_name='Настройки Header')),
                ('footer_settings', models.JSONField(blank=True, default=dict, verbose_name='Настройки Footer')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликован')),
                ('is_public', models.BooleanField(default=True, verbose_name='Публичный доступ')),
                ('views_count', models.IntegerField(default=0, verbose_name='Количество просмотров')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Опубликован')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название страницы')),
                ('slug', models.SlugField(max_length=255, verbose_name='URL-адрес')),
                ('html_content', models.TextField(blank=True, verbose_name='HTML содержимое')),
                ('css_content', models.TextField(blank=True, verbose_name='CSS содержимое')),
                ('json_content', models.JSONField(blank=True, default=dict, verbose_name='JSON данные')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликована')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='api.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['user', 'slug'], name='api_project_user_id_bcfeea_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['slug', 'is_published'], name='api_project_slug_03551f_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_published'], name='api_project_is_publ_d36767_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('user', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together={('project', 'slug')},
        ),
    ]
