# Generated by Django 5.0.1 on 2025-11-12 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='saved_blocks',
            field=models.JSONField(blank=True, default=dict, verbose_name='Сохраненные блоки'),
        ),
    ]
