# Generated by Django 5.0.1 on 2025-11-13 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_project_saved_blocks_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='deployed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Задеплоен'),
        ),
        migrations.AddField(
            model_name='project',
            name='deployed_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL деплоя'),
        ),
    ]
