# Generated by Django 5.0.1 on 2025-11-13 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_project_deployed_at_project_deployed_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название блока')),
                ('block_id', models.SlugField(max_length=255, unique=True, verbose_name='ID блока')),
                ('category', models.CharField(choices=[('Базовые', 'Базовые'), ('Структура', 'Структура'), ('Формы', 'Формы'), ('Медиа', 'Медиа'), ('Навигация', 'Навигация'), ('Другое', 'Другое')], default='Другое', max_length=50, verbose_name='Категория')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('preview', models.CharField(blank=True, max_length=10, null=True, verbose_name='Превью (эмодзи)')),
                ('content', models.TextField(verbose_name='HTML содержимое')),
                ('label', models.TextField(blank=True, null=True, verbose_name='Label с превью (HTML)')),
                ('media', models.TextField(blank=True, null=True, verbose_name='SVG иконка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('attributes', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные атрибуты')),
                ('traits', models.JSONField(blank=True, default=list, verbose_name='Traits для редактирования')),
                ('component_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип компонента GrapesJS')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_blocks', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Кастомный блок',
                'verbose_name_plural': 'Кастомные блоки',
                'ordering': ['category', 'order', 'name'],
                'indexes': [models.Index(fields=['block_id', 'is_active'], name='api_customb_block_i_c1d958_idx'), models.Index(fields=['category', 'is_active'], name='api_customb_categor_df53a5_idx'), models.Index(fields=['is_active'], name='api_customb_is_acti_66b9d6_idx')],
            },
        ),
    ]
