# Generated by Django 5.0.1 on 2025-11-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_customblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='deploy_type',
            field=models.CharField(choices=[('vps', 'VPS (свой сервер)'), ('subdomain', 'Поддомен конструктора')], default='vps', max_length=20, verbose_name='Тип деплоя'),
        ),
        migrations.AddField(
            model_name='project',
            name='subdomain',
            field=models.SlugField(blank=True, max_length=100, null=True, verbose_name='Поддомен'),
        ),
    ]
