# Generated by Django 5.0.1 on 2025-11-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_add_deploy_type_subdomain'),
    ]

    operations = [
        migrations.CreateModel(
            name='VPSServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название сервера')),
                ('host', models.CharField(max_length=255, verbose_name='IP адрес или домен')),
                ('port', models.IntegerField(default=22, verbose_name='SSH порт')),
                ('username', models.CharField(max_length=100, verbose_name='SSH пользователь')),
                ('password', models.CharField(max_length=255, verbose_name='SSH пароль')),
                ('deploy_path', models.CharField(default='/var/www/deployed', max_length=500, verbose_name='Базовый путь для деплоя')),
                ('domain', models.CharField(blank=True, max_length=255, null=True, verbose_name='Домен (для поддоменов)')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email для SSL сертификатов')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_default', models.BooleanField(default=False, verbose_name='Сервер по умолчанию для поддоменов')),
                ('nginx_config_enabled', models.BooleanField(default=True, verbose_name='Автоматически настраивать Nginx')),
                ('ssl_enabled', models.BooleanField(default=False, verbose_name='Использовать SSL по умолчанию')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'VPS сервер',
                'verbose_name_plural': 'VPS серверы',
                'ordering': ['-is_default', 'name'],
                'indexes': [models.Index(fields=['is_active', 'is_default'], name='api_vpsserv_is_acti_8d96ef_idx')],
            },
        ),
    ]
