# Generated by Django 5.0.1 on 2025-11-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_add_vps_server'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='deploy_type',
            field=models.CharField(choices=[('vps', 'VPS (свой сервер)'), ('builder_vps', 'VPS сервер конструктора')], default='vps', max_length=20, verbose_name='Тип деплоя'),
        ),
    ]
